### ISSUE TITLE
Region not being respected

### ISSUE THREAD

**Issue by huang-jy** [rusher81572/cloudExplorer#54]
First time running the app, we get this:

Checking for update......
Installed Version: 8.22
Error: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
Error: No saved configurations found.

Then when entering the access key and secret and using the region of "default" or "a valid region" (e.g. eu-west-1), nothing is listed on the bucket list. But no errors either displayed either...

**Comment by huang-jy** [comment]
Fixed by using a different version of java (openjdk instead of Oracle), but now getting a different issue.

When applying a function, it defaults to "us-east-1", even though the region is specified on the account config:

Error Message:    The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-west-2' (Service: Amazon S3; Status Code: 400; Error Code: AuthorizationHeaderMalformed; Request ID: F3BB0A1EFD6A4BC7)

**Comment by rusher81572** [comment]
Hello, @huang-jy . Thanks for reporting this. I am looking into it.  I found the issue but I am not sure how to best move forward. I am not sure if it is worth it supporting the creation of buckets in different regions anymore because the behavior is different in each region. For example, in us-west-1, you do not need to enter a region to use the default. In other regions. In other regions like eu-west-1, I enter us-west-1 for the region when I create a bucket and it still goes to Ireland and not the US. Is this feature important?  A workaround is to add another account for the specific region

**Comment by huang-jy** [comment]
I got this message simply by opening the bucket in the interface. The bucket was created in eu-west-2. Entering nothing as region seems to default it to us-east-1. Entering eu-west-2 on the account configuration still makes it somehow default to us-east-1. So, yes, this feature is important as I can't really use the application otherwise :P

**Comment by rusher81572** [comment]
@huang-jy Thanks. In the original code, it would ignore the region and default to the sdk default region. May you please test this dev build? https://cloudexplorer.s3.amazonaws.com/cloudExplorer-dev.zip

**Comment by huang-jy** [comment]
That didn't seem to work either:

```
Checking for update......
Installed Version: 8.23
Latest version is: 8.22
No update available.


Loading configuration: https://s3.amazonaws.com


Please wait, loading files.

The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-west-2' (Service: Amazon S3; Status Code: 400; Error Code: AuthorizationHeaderMalformed; Request ID: EF98E3CE4744F43C)

No files found.


```

**Comment by rusher81572** [comment]
Hmmm.. This is hard to explain. I think there maybe limitations with the S3 API. What country are you in? Maybe S3 is routing you to different locations?

My endpoint is s3.amazonaws.com. I can create buckets fine in eu-west-1 and us-west-1 when I use us-west-1 as the region.  

Basically, I can do anything anywhere with that config and have limitations such as deleting buckets from other regions when connecting directly to the non s3.amazonaws.com endpoints.

When connecting to s3.amazonaws.com using us-east-1 as the region, I get the same problem as you. 

If you use us-east-1 and s3.amazonaws.com, do the issues go away?

**Comment by huang-jy** [comment]
I am in the uk, with the bucket in London also.

This is my config

Host URL: http://s3.amazonaws.com
Port: 443
Region: eu-west-2
Name: [blank]

Nowhere am I setting us-east-1....

Even if I use `aws configure list`, I get a default regions of eu-west-1 (Ireland)

So, somewhere the app is picking up a region of us-east-1 and overriding my value of eu-west-2

**Comment by rusher81572** [comment]
Hmm...

I was not able to reproduce it. Why are you using http for the host URL but using port 443? I think that may be your problem. 

Here is my config that worked fine:

Host URL: https://s3.amazonaws.com
Port: 443
Region: eu-west-2

I created a bucket in eu-west-1 and was able to delete it.

**Comment by huang-jy** [comment]
That was a typo on my part, I do also have https://s3.amazon.com and port 443

And I'm not creating a bucket, I'm trying to list the contents of the bucket.

**Comment by huang-jy** [comment]
Okay, so I created a bucket from the app, and it seems okay. Which is weird, the other bucket I created outside of the app and it is having problems with it. :/

**Comment by huang-jy** [comment]
After some tinkering with the IAM policies (they were too open) it now seems to be working. However, a few further things.

1. When using Oracle Java, uploading fails with this
`Exception in thread "Thread-5" java.lang.NoClassDefFoundError: javax/activation/MimetypesFileTypeMap
	at cloudExplorer.Put.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.ClassNotFoundException: javax.activation.MimetypesFileTypeMap
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:532)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:186)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:473)
	... 2 more
Exception in thread "Thread-6" java.lang.NoClassDefFoundError: javax/activation/MimetypesFileTypeMap
	at cloudExplorer.Put.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:844)
`

When using OpenJDK, it's fine. (On a linux box)

2. Using "Graph" throws a NullPointException
`Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at cloudExplorer.NewJFrame.jMenuItem26ActionPerformed(Unknown Source)
	at cloudExplorer.NewJFrame.access$5600(Unknown Source)
	at cloudExplorer.NewJFrame$57.actionPerformed(Unknown Source)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
`

But these are minor problems. I'm closing this issue as the region issue seems resolved by creating the bucket from within the app (weirdly).

**Comment by rusher81572** [comment]
Thank you so much @huang-jy for helping me find this issue. I will go ahead and release 8.23 now with the region fix

**Comment by rusher81572** [comment]
Hello @huang-jy .

Just a follow up , the latest release 10.02 should address all of the region issues.
