### ISSUE TITLE
jar file does not execute with Java 8

### ISSUE THREAD

**Issue by marudy** [rusher81572/cloudExplorer#62]
Hi there @rusher81572,

I wanted to try out your client but couldn't because I am getting this error:

```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: cloudExplorer/CloudExplorer has been compiled by a more recent version of the Java Runtime (class file version 54.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
```

After Googling I ended up to this [thread](https://stackoverflow.com/questions/47876051/has-been-compiled-by-a-more-recent-version-of-the-java-runtime-class-file-versi) explaining that the jar file is compiled with Java 9 and is not compliant with Java 8. Could you recompile it and make it compliant for Java 8 as well?

I'm running
```
Ubuntu 16.04

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
```

Thanks,
Tasos

**Comment by rusher81572** [comment]
Hello, Tasos.

The only difference in version 12 is support for Java 9 and 10. If you need Java 8 support, please use v11 https://cloudexplorer.s3.amazonaws.com/10/cloudExplorer-11.zip

**Comment by marudy** [comment]
Thanks for the quick response.

I will try it and close the issue if everything works fine :smile: 

I see you mention it in Download section but maybe consider putting the information closer to the `Donwload` link?? I missed it although the info was there.

Thanks again,
Tasos
